### ISSUE TITLE
Please build docker-1.9.0 for arm.

### ISSUE THREAD

**Issue by vimagick** [umiddelb/armhf#13]
I'm trying to build it on my own.

```
$ ./build --arm 6 1.9.0
...
Fetched 2527 kB in 1min 3s (40.1 kB/s)
Reading package lists...
Reading package lists...
Building dependency tree...
Reading state information...
E: Unable to locate package ubuntu-zfs
The command '/bin/sh -c apt-get update && apt-get install -y    apparmor        aufs-tools      automake        bash-completion    btrfs-tools     build-essential         createrepo      curl    dpkg-sig        git     iptables        libapparmor-dev    libcap-dev      libsqlite3-dev  mercurial       parallel        python-mock     python-pip      python-websocket  reprepro         ruby1.9.1       ruby1.9.1-dev   s3cmd=1.1.0*    ubuntu-zfs      libzfs-dev      --no-install-recommends' returned a non-zero code: 100
Makefile:74: recipe for target 'build' failed
make: *** [build] Error 1
```

I found there is no `ubuntu-zfs_8~trusty_armhf.deb` in [PPA](http://ppa.launchpad.net/zfs-native/stable/ubuntu/pool/main/u/ubuntu-zfs/).
I don't know how to solve it. Please help. Thanks!

**Comment by vimagick** [comment]
I didn't notice that [Dockerfile](https://github.com/umiddelb/armhf/blob/master/Dockerfile.armv7#L59-L60) was modified further. I'll try it again.

---

I still cannot build it successfully:

```
Step 26 : RUN set -x    && export GOPATH="$(mktemp -d)"         && git clone https://github.com/docker/notary.git "$GOPATH/src/github.com/docker/notary"   && (cd "$GOPATH/src/github.com/docker/notary" && git checkout -q "$NOTARY_COMMIT")      && GOPATH="$GOPATH/src/github.com/docker/notary/Godeps/_workspace:$GOPATH"                 go build -o /usr/local/bin/notary-server github.com/docker/notary/cmd/notary-server        && rm -rf "$GOPATH"
 ---> Running in e9308c51f18a
+ mktemp -d
+ export GOPATH=/tmp/tmp.sNR3vKhAM1
+ git clone https://github.com/docker/notary.git /tmp/tmp.sNR3vKhAM1/src/github.com/docker/notary
Cloning into '/tmp/tmp.sNR3vKhAM1/src/github.com/docker/notary'...
+ cd /tmp/tmp.sNR3vKhAM1/src/github.com/docker/notary
+ git checkout -q 8e8122eb5528f621afcd4e2854c47302f17392f7
+ GOPATH=/tmp/tmp.sNR3vKhAM1/src/github.com/docker/notary/Godeps/_workspace:/tmp/tmp.sNR3vKhAM1 go build -o /usr/local/bin/notary-server github.com/docker/notary/cmd/notary-server
# github.com/dvsekhvalnov/jose2go/kdf
tmp/tmp.sNR3vKhAM1/src/github.com/docker/notary/Godeps/_workspace/src/github.com/dvsekhvalnov/jose2go/kdf/nist_sp800_56a.go:20: constant 4294967295 overflows int
tmp/tmp.sNR3vKhAM1/src/github.com/docker/notary/Godeps/_workspace/src/github.com/dvsekhvalnov/jose2go/kdf/pbkdf2.go:23: constant 4294967295 overflows int
The command '/bin/sh -c set -x  && export GOPATH="$(mktemp -d)"         && git clone https://github.com/docker/notary.git "$GOPATH/src/github.com/docker/notary"   && (cd "$GOPATH/src/github.com/docker/notary" && git checkout -q "$NOTARY_COMMIT") && GOPATH="$GOPATH/src/github.com/docker/notary/Godeps/_workspace:$GOPATH"              go build -o /usr/local/bin/notary-server github.com/docker/notary/cmd/notary-server        && rm -rf "$GOPATH"' returned a non-zero code: 2
Makefile:75: recipe for target 'build' failed
make: *** [build] Error 1
```

**Comment by umiddelb** [comment]
I'm about to build Docker 1.9.0 for ARMv7, just wait a couple of minutes ...

**Comment by vimagick** [comment]
Thank you very much! :+1:

**Comment by umiddelb** [comment]
done

**Comment by vimagick** [comment]
:smile: I've built [docker-1.9.1](https://github.com/vimagick/rpi-bin/wiki/docker) successfully on Raspberry Pi 2.

**Comment by umiddelb** [comment]
starting with docker version 1.10 docker for arm will be build by the [official repository](https://github.com/docker/docker). You can try it with the current development tree.

**Comment by aerodame** [comment]
Uli we built up a 1.9.1 on a bunch of CuBox units and have this consistent devmapper fault that occurs all the time when building images from Dockerfiles.   Have you seen that issue?   You can succeed in eventually completing images by repeating the docker build until it complete but it is a royal pain.

Not sure which file system would be best for these mx6 arm devices.

Sent from my iPhone

On Jan 16, 2016, at 3:50 AM, Uli Middelberg <notifications@github.com<mailto:notifications@github.com>> wrote:

starting with docker version 1.10 docker for arm will be build by the official repositoryhttps://github.com/docker/docker. You can try it with the current development tree.

##

**Comment by umiddelb** [comment]
Hi Steve,
hm, this sounds weird. Do you mind opening a new github issue and sharing some information about your environment:
- which device: CuBox (Marvell Armada5XX based) or CuBox-i (Freescale/NXP imx6 based)?
- which kernel (source code repository)?
- the output of [check-config.sh](https://raw.githubusercontent.com/docker/docker/master/contrib/check-config.sh)

Docker can use several storage backends, the devicemapper is used as a last resort (it's really slow).
I'm using overlayfs on my CuBox-i running a 4.4 vanilla mainline Linux kernel. I haven't used Docker 1.9.1 so far, only 1.9.0 and 1.10.0-dev.

**Comment by aerodame** [comment]
Will do!

Sent from my iPhone

On Jan 17, 2016, at 11:38 AM, Uli Middelberg <notifications@github.com<mailto:notifications@github.com>> wrote:

Hi Steve,
hm, this sounds weird. Do you mind opening a new github issue and sharing some information about your environment:
-   which device: CuBox (Marvell Armada5XX based) or CuBox-i (Freescale/NXP imx6 based)?
-   which kernel (source code repository)?
-   the output of check-config.shhttps://raw.githubusercontent.com/docker/docker/master/contrib/check-config.sh

Docker can use several storage backends, the devicemapper is used as a last resort (it's really slow).
I'm using overlayfs on my CuBox-i running a 4.4 vanilla mainline Linux kernel. I haven't used Docker 1.9.1 so far, only 1.9.0 and 1.10.0-dev.

##
