### ISSUE TITLE
semi-automatic update

### ISSUE THREAD

**Issue by kennethlimcp** [umiddelb/armhf#14]
Hey @umiddelb , 

can you advice on how you update your devices with a new docker version each time you build a new one?

Thanks! :)

**Comment by umiddelb** [comment]
```
sudo apt-get update
sudo apt-get -y upgrade 
sudo apt-get -y autoremove
sudo service docker stop
curl -sSL https://github.com/umiddelb/armhf/blob/master/bin/docker-1.9.0?raw=true | sudo dd of=/usr/bin/docker
sudo service docker start
```

There is a recent Ubuntu package update for 14.04 bumping docker to version 1.6.2 and renaming the service from `docker.io` to `docker`.

**Comment by kennethlimcp** [comment]
Thanks! :)
