### ISSUE TITLE
Go Path in Dockerfile

### ISSUE THREAD

**Issue by aerodame** [umiddelb/armhf#16]
I used to be able to build docker on my targets using the normal steps:

$ git clone -b 'v1.9.1' --single-branch https://github.com/docker/docker.git
$ cd docker
$ curl -L https://github.com/umiddelb/armhf/raw/master/Dockerfile.armv7 > Dockerfile
$ sudo make build
$ sudo make binary
Now, I get a make error ...at STEP 41:

go get -v -d github.com/cpuguy83/go-md2man package code.google.com/p/go.net/html: unable to detect version control system for code.google.com/ path
This kills the make. Is this a known issue?

**Comment by umiddelb** [comment]
@aerodame 
You may issue a PR to the docker/docker repository too, since they are affected by this change as well (external dependency change).
