### ISSUE TITLE
Odroid-C2 make instructions error

### ISSUE THREAD

**Issue by mad-ady** [umiddelb/armhf#21]
You made a typo under the Odroid-C2 build instructions on this page: https://github.com/umiddelb/armhf/wiki/How-To-compile-a-custom-Linux-kernel-for-your-ARM-device - namely:

$ sudo cp arch/arm/boot/Image arch/arm/boot/dts/meson64_odroidc2.dtb /media/boot

should be

$ sudo cp arch/arm64/boot/Image arch/arm64/boot/dts/meson64_odroidc2.dtb /media/boot 

Thanks for all your work!

**Comment by umiddelb** [comment]
Fixed! Thank you Adrian!
