### ISSUE TITLE
Vielen Dank fürs Ergänzen / Korrigieren 

### ISSUE THREAD

**Issue by umiddelb** [umiddelb/armhf#23]
Hallo @tobiasjakobi ,

Vielen Dank fürs Ergänzen / Korrigieren! 

Viele Grüße nach Bielefeld! (Ich bin vor 20 Jahren für meinen ersten Job an der Uni nach Bielefeld gezogen)

**Comment by ghost** [comment]
Hallo Uli,

keine Ursache!

Das mit dem Umziehen steht mir vermutlich auch noch bevor, wenn ich mit meinem PhD fertig bin. :)

Mit besten Grüßen,
Tobias
