### ISSUE TITLE
Add higher frequencies for XU4 on ioft repository

### ISSUE THREAD

**Issue by jobenvil** [umiddelb/armhf#28]
I would like to have [this patch](https://github.com/torvalds/linux/commit/cd8a88d523598df5baa8039611680afac35f5487) applied by default to the ioft master branch. Is this realistic?

**Comment by umiddelb** [comment]
It's already applied, see [here](https://github.com/torvalds/linux/compare/master...ioft:master), commit [0dacf5f](https://github.com/torvalds/linux/commit/0dacf5f4837b854e8753780866eb325bf803e0c0).

**Comment by jobenvil** [comment]
11 days ago was the commit. Sorry for not check. My kernel was compiled some more weeks ago.
