### ISSUE TITLE
Cannot start docker container

### ISSUE THREAD

**Issue by nephilim75** [umiddelb/armhf#29]
Hello

I need some assistance on an issue that I am facing. I followed your [instructions](https://github.com/umiddelb/armhf/wiki/Get-Docker-up-and-running-on-the-RaspberryPi-%28ARMv6%29-in-four-steps-%28Wheezy%29) and to me it looks like it is working. Please see this [record](http://paste.ubuntu.com/23163794/).

Now I try to run a container called Collabora. I used this command:
`docker run -t -d -p 9980:9980 -e "domain=sub\.domain\.com" --cap-add MKNOD collabora/code`

but it fails. Here is the [error log](http://paste.ubuntu.com/23163936/).

Any idea how to get this fixed? Or just a hint where I can start to investigate? Is this might be an collabora container issue?

Your assistance is highly appreciated.

Kind regards
//nephilim

**Comment by kennethlimcp** [comment]
You will need to use `armhf` compatible images like https://hub.docker.com/r/container4armhf/armhf-alpine/

**Comment by nephilim75** [comment]
Not sure, if I handled it the right way. Pls see the [error log](http://paste.ubuntu.com/23165589/) I received now. Did I miss anything?

**Comment by umiddelb** [comment]
> Error response from daemon: Cannot start container 839c5c152137ff9acbe51bbf1a72e88f9717b1cdc21f5cf84d4472cd6208c017: [8] System error: exec format error

The binary in your image isn't made for arm (probably it's made for x86). You need to find out the Dockerfile for `collabora/code` and replace the base image by its armhf equivalent.

**Comment by nephilim75** [comment]
Sorry to say, but I do not know how. I am newbie on this. Any hint for me?

**Comment by umiddelb** [comment]
Hm, you may ask the creator of the Docker image to provide a version for armhf [here](https://www.collaboraoffice.com/code/) or [here](https://hub.docker.com/r/collabora/code/), since they don't disclose the build procedure. :(

**Comment by nephilim75** [comment]
I will try this. Wrote them today. Will get back once I got a reply. Thank you.
