### ISSUE TITLE
Uboot 2015 version for Odroid C1

### ISSUE THREAD

**Issue by floion** [umiddelb/armhf#31]
Hi,
in https://github.com/umiddelb/armhf/wiki/Get-more-out-of-%22Das-U-Boot%22 I see you mention u-boot 2015 version for the Odroid C1. Do you know where these sources are?

Thank you

**Comment by umiddelb** [comment]
Hi,
IHMO `Jul 28 2015´ ist the built date only, not a reference to the underlying u-boot version (which is 2011-03). The source code can be found [here](https://github.com/hardkernel/u-boot/tree/odroidc-v2011.03).

**Comment by floion** [comment]
Correct, that's the build date :(
Thanks for the eye-opener, will close this issue
Sigh ...
