### ISSUE TITLE
[C1] cgroup hierarchy: nonexistent??

### ISSUE THREAD

**Issue by kennethlimcp** [umiddelb/armhf#5]
Hey @umiddelb,

i also tried out the latest Ubuntu from Hardkernel and i ran the Docker check just to be sure.

Seems like by default, they did not enable the `- cgroup hierarchy: nonexistent??`

There's a script to do so as mentioned:  https://github.com/tianon/cgroupfs-mount

So i thought i would mention to you in case someone asked the same thing. I will test out Docker 1.5.0 and see how it goes and report back.

Thanks!

**Comment by umiddelb** [comment]
Hi @kennethlimcp 

At least you have to make sure that the following packages are installed:

```
sudo apt-get install lxc aufs-tools cgroup-lite apparmor docker.io 
```

cgroup hierarchy is provided by the package cgroup-lite not by the kernel.

**Comment by kennethlimcp** [comment]
That worked thanks! :)

**Comment by umiddelb** [comment]
you're welcome! Which Ubuntu image did you take for installing the C1?

**Comment by kennethlimcp** [comment]
I'm using the 14.04 image from Hardkernel. Managed to update to Docker 1.5.0 as well :)

Haven't gotten my Hummingboard up since i'm used to using a `.img` file.

There's a great repo here and i think his version supports all the Docker requirements except AUFS.

https://github.com/igorpecovnik

Would be great if he can add it!

**Comment by umiddelb** [comment]
so you've taken the image from [here](http://odroid.in/ubuntu_14.04lts/)?

**Comment by kennethlimcp** [comment]
Yup that's right!
