### ISSUE TITLE
Mention buildroot?

### ISSUE THREAD

**Issue by paralin** [umiddelb/armhf#7]
I'm using Docker under Buildroot at the moment (cross compiling docker, aufs, etc). Might be interesting to mention it.

Docker hasn't been merged yet but probably will be in the coming weeks.

See http://github.com/paralin/buildroot

**Comment by umiddelb** [comment]
Hi,

haven't heard about buildroot before ... very comprehensive. I've tried to simplify the process setting up ubuntu core + docker + linux kernel + boot loader for my own devices ([z2d](https://github.com/umiddelb/z2d)).   

You may issue a pull request to extend this list [here](https://github.com/veggiemonk/awesome-docker), which has a much broader audience ;)
