### ISSUE TITLE
Trying docker 1.8.1 Fails

### ISSUE THREAD

**Issue by aerodame** [umiddelb/armhf#9]
Uli, still compiling 1.7.1 but initially I tried building 1.8.1 and received the following error...

$ git clone -b 'v1.8.1' --single-branch https://github.com/docker/docker.git 

$ sudo make build

... 
Step 14 : RUN curl -sSL ...
2015/08/25 16:17:23 **finalize namespace drop capabilities operation not permitted** 
2015/08/25 18:17:23 The command [/bin/sh -c curl -sSL https://golang.org/dl/go${GO_VERSION}.src.tar.gz | tar -v -C /usr/local -xz && mkdir -p /go/bin] **returned a non-zero code: 1**
## make: **\* [build] Error 1

Actually 1.7.1 build just failed as well.  Similar problem but at a different step.

Removing intermediate container 89c1d0ca770d
Step 40 : ENV TOMLV_COMMIT 9baf8a8a9f2ed20a8e54160840c492f937eeaf9a
 ---> Running in 6974271ca401
 ---> d9662cb19f3c
Removing intermediate container 6974271ca401
**Step 41** : RUN set -x && git clone https://github.com/BurntSushi/toml.git /go/src/github.com/BurntSushi/toml && (cd /go/src/github.com/BurntSushi/toml && git checkout -q $TOMLV_COMMIT)
 ---> Running in db87fab2b11a
2015/08/25 17:32:19 **finalize namespace drop capabilities operation not permitted**
2015/08/25 19:32:20 The command [/bin/sh -c set -x && git clone https://github.com/BurntSushi/toml.git /go/src/github.com/BurntSushi/toml && (cd /go/src/github.com/BurntSushi/toml && git checkout -q $TOMLV_COMMIT)] returned a non-zero code: 1
make: **\* [build] Error 1

Just curious if you have seen the same and/or know how to get past this error.

**Comment by umiddelb** [comment]
Steve, the error you're getting (`finalize namespace ...`) is a known [bug](https://github.com/docker/docker/issues/4556) in Docker 1.0.1.
Just repeat 'make build', the error doesn't occur every time you invoke docker. You can download my Docker 1.7.1 binary for ARM available on GitHub, if you're impatient.

Docker 1.8.0/1 doesn't compile on ARM for various reasons, there are some open [issues](/docker/docker/issues/15053) on GitHub.

**Comment by aerodame** [comment]
I did finally download your binary and am starting to test it now...  Exhausting process.  Thanks!

Sent from my iPhone

On Aug 25, 2015, at 11:16 AM, "Uli Middelberg" <notifications@github.com<mailto:notifications@github.com>> wrote:

Steve, the error you're getting (finalize namespace ...) is a known bug in Docker 1.0.1.
Just repeat 'make build', the error doesn't occur every time you invoke docker. You can download my Docker 1.7.1 binary for ARM available on GitHub, if you're impatient.

Docker 1.8.0/1 doesn't compile on ARM for various reasons, there are some open issues on GitHub.

##

**Comment by umiddelb** [comment]
> I did finally download your binary and am starting to test it now...  Exhausting process.  Thanks!

I've tried to automate the process setting up ubuntu core + docker for the cubox-i (and other ARMv7 devices as well). You may take a look [here](/umiddelb/z2d). The [xilka kernel](http://xilka.com/kernel) works well with docker.

**Comment by umiddelb** [comment]
I believe you're fine running Docker on your CuBox.
I'll close this issue now.
